### ISSUE TITLE
Funkcja zwracająca pozycje wiązki x y na podstawie numeru napełnienia RHIC 

### ISSUE THREAD

**Issue by ladamczy** [ladamczy/STAR-Analysis#1]
W kartotece share znajduje się plik beamLine.txt z pozycja x i y beamu w 2017 roku. 
Na stronie głównej jest link do strony z data początku i końca napełnień RHIC.

**Comment by PatrycjaMalinowska** [comment]
Próbuję utworzyć plik z runem i pozycją wiązki, ale nie wiem czy powyższy opis odpowiada plikowi runs_2017.txt.
Założyłam że kolumna A to numer runu, B czas końcowy, a E czas początkowy runu. Jednak przy takim założeniu, część runów rozciągałaby się na okres miesiąca, jak na załączononym obrazku.
 
![obraz](https://github.com/ladamczy/STAR-Analysis/assets/130799536/71cc3932-3ee8-41d5-bce3-791beb46fe5a)

**Comment by ladamczy** [comment]
Numer runu to pozycja J. Tę informacje mamy w danych. Numery ranów maja dziury bo koduja one rok i dzień 
np. 18 035 016 - to run z 2017 (18) roku , 35 dzień roku (4 luty), 16-ty ran w dniu 4 lutego  (016) 
  
Poczatek ranu to pozycja E (Dzień i godzina) 
Nie ma czasu końca ranu. Prosze przyjąć że czas końca ranu to czas początku nasępnego ranu na liscie.
Pozycja A to jest kolejny numer na liscie ranów. Czyli ran 18035016 był 164500 ranem w historii STAR'a.

**Comment by ladamczy** [comment]
czy ten kod jest juz w repozytorium ?   Wydaje mi sie że nie.

**Comment by PatrycjaMalinowska** [comment]
dodałam plik z numerami run i pozycją wiązki do katalogu share - można używać poprzedniej funkcji wraz z tym plikiem i przekazanym do niej numerem run.

**Comment by ladamczy** [comment]
zamykam to issue.  W nowych danych mamy te informacje w drzewie.
