### ISSUE TITLE
preselekcja próbki zero-bias

### ISSUE THREAD

**Issue by ladamczy** [ladamczy/STAR-Analysis#18]
próbke zero-bias będziemy analizowali wielokrotnie. Myśle że warto sobie przygotować osobne pliki tylko z tym trygerem
bez żadnych selekcji.

**Comment by AddahDraggon** [comment]
Są przygotowane

**Comment by ladamczy** [comment]
Ile to jest przypadków i jaki rozmiar całej próbki ?

**Comment by AddahDraggon** [comment]
9 304 845 przypadków
2214 plików
15.8 GB

**Comment by ladamczy** [comment]
tak jak w innym issue, stare dane sa dobre.
