### ISSUE TITLE
Początkowa analiza inkluzywna

### ISSUE THREAD

**Issue by ladamczy** [ladamczy/STAR-Analysis#5]
1. zaczynamy od próbki jeden werteks i cztery ślady zmaczowane z ToF.
Suma ładunków nie musi być 0. Ale przynajmniej jedna para o przeciwnych znakach.

rezygnujemy z cięc nz DCAxy, DCAz . Zostaje |eta|<0.9 i pT>0.2

Szukamy pary śladów o przeciwnych znakach w oknie masy(szerokim)  K0.
Przy kilku  parach w oknie masy wybieramy pare bliższą   masy K0.
Druga para tworzy PV (primary werteks) bez żadnych warunków.

Interesuja nas rozkłady:

masy K0 w szerokim zakresie masy
dca(pipi)K0 , R K0 w wąskim zakresie masy
dca(pipi)PV , R PV pod warunkiem że druga para (K0) w wąskim zakresie masy.
Odległość między PViKO dla przypadków w wąskim zakresie masy K0.

**Comment by ladamczy** [comment]
1. Prosze zrobić rozkłady xiE i xiW dla przypadków przechodzących przez ciecia fiducial na protony.  Musimy zrozumieć protony które maja xi>1 które według mnie nie moga miec miejsca
2. Prosze stosowac konwencje że jedna para śladów jest kndydatem na K0 , czyli spełnia wszystkie ciecia sugerowane prze zemnie w prezentacji. Druga para ma  pochodzuć z PV czyli spełnia tylko ciecie na DCADaugthers i ma decay vertex blisko beam-line < 1.5 cm

**Comment by AddahDraggon** [comment]
Protonów z xi>1 nie ma, logarytm z xi ujemnego jest interpretowany jako NaN, który jest wyświetlany przez histogram jako overflow - po zastosowaniu cięcia na xi<0 (tylko do uzupełniania histogramów protonów) problem znikł (wycinany jest wtedy cały przypadek, tzn. oba protony, nawet jeśli jeden jest ok). Załączam wykresy log10(xi) dla obu gałęzi.

[logW.pdf](https://github.com/ladamczy/STAR-Analysis/files/13627951/logW.pdf)
[logE.pdf](https://github.com/ladamczy/STAR-Analysis/files/13627952/logE.pdf)

**Comment by AddahDraggon** [comment]
Jutro do południa zaimplementuję lepsze wyznaczanie wierzchołka, chciałbym się spytać natomiast czy w przypadku gdy nie ma kandydata na wierzchołek spełniającego tych dwóch cięć na DCADaughters i odległość od beamline, to czy taki przypadek odrzucamy czy bierzemy obecnie wyznaczony wierzchołek? I jeśli to drugie, to czy współrzędne XY poprawiamy za pomocą slope, czy ustawiamy takie jakie są wyczytane w pliku (bo zakładam że współrzędną z bierzemy z `tempUPCpointer->getVertex(0)->getPosZ()`).

**Comment by AddahDraggon** [comment]
Nie jestem pewien, czy nie popełniłem gdzieś błędu, ale dwa warunki wzięte z prezentacji
```
bool K0test3 = tempParticle->pointingAngleHypo()>0.925;
bool K0test4 = tempParticle->DCABeamLine()<1.5;
```
jeśli nie są ignorowane, kompletnie negują wykrywane K0.  Sprawdziłem ich wartości i obie funkcje (`pointingAngleHypo` i `DCABeamLine`) zwracają NaN.

**Comment by ladamczy** [comment]
Uwagi do wszystkich postów po kolei:
1. Przypadków z xi<0 nie powinnićmy odrzucać tak od razu. Dlatego sugeruję aby narysował Pan również rozkłady xi a nie tylko log(xi) aby zobaczyć ile mamy przypadków z ujemnymi  xi.  Z Pana analizy PYTHIA8 wynika że xi_true>0.005  ale na poziomie   detektorowym  xi_true=0.005 moze mieć wartość  np. ujemną . -0.00001.  Problem jest z rysowaniem log(xie*xiw). Niech Pan narazie wymusi  if( xiE<0.005 || xiW<0.005 ) log(xiE*xiW)=2*log(0.005) . Bedziemy pamiętać że wrtość log(xiE*xiW)=2*log(0.005) zawiera wszystkie problematyczne przypadki z ujemnymi lub bardzo małymi xi. Podobnie  
   if( xiE<0.005 || xiW<0.005 )  ln(xiW/xiE) = 0     
2. Nie jestem pewien czy dobrze rozumiem o czym Pan pisze :
   "nie ma kandydata na wierzchołek spełniającego tych dwóch cięć na DCADaughters i odległość od beamline," 
W pierwszym podejściu analizujemy przypadki 4 ToF. Gdzie 2 slady (+-) spełniaja rekomendowane ciecia na V0
(DCADaughters <1.5, DCABeamline<1.5, Pointing angle>0.925 , 0.46<masa<0.53   pozostałe dwa ślady (w dowolnej konfiguracji ładunkowej)  spełniaja tylko ciecie na DCADaughters<1.5,  DCABeamline<1.5, (bez pointinAngle i masy)
czyli jest to kandydat na collision vertex.   Na koniec warto zrobic rozkład róznicy z-towych składowych wierzchołków
produkcji  obu par. 
3. Nie powinno być NaN. Czy parametr vtx jest ustawiony na np. (0,0,0) ? lub getVertex() ?
   Może się również zdarzyć że pary z bardzo złym DCADaughters maja problemy z pointing angle i lub DCABeamline. 
   Czy problem NaN dotyczy również par z  DCADaughters <1.5 ? Rozumiem, ze tak b wtedy coś by Panu zostało. 
  Podejrzewam jakiś bład w programie czy masy pionów ma Pan w GeV ?

**Comment by AddahDraggon** [comment]
Z NaN się uporałem - okazało się że program czyta względne ścieżki do plików od poziomu folderu "home" zamiast od pozycji jego samego. Po korekcie nie mam przypadków z NaN. Przesyłam w załączeniu wygenerowane wykresy (13 i 14 to Xi odpowiednio wschodnie i zachodnie w obszarze anomalnym, tzn. Xi<0).

[AnaOutput_Inclusive_analysis_with_STUPCV0.pdf](https://github.com/ladamczy/STAR-Analysis/files/13697201/AnaOutput_Inclusive_analysis_with_STUPCV0.pdf)

Punkt 2 - chodzi mi o to, że w 1168 przypadków druga para (ta, która ma stać się collision vertex) nie spełnia dwóch wymaganych warunków. Czy w takim przypadku mam ją zignorować całkowicie, użyć PV z danych, z poprawą z pliku csv?

**Comment by ladamczy** [comment]
Nie rozumim jak problem ze ścieżkami do plików moze wygenerować NaN dla pewnych zmiennych a dla innych zmiennych nie. Ale nie ma to juz znaczenia. 

Rozkłady xi (strony 13 i 14) prosze narysować w pełnym zakresie a nie obinać  na xi<0.002. Czyli od -0.05 do + 1.0. 
Tam się spodziewmay Gaussa o średniej 0 + opadający ~wykładniczo  rozkład po stronie dodatnich xi. Interesuje nas 
szerokość tego Gaussa o średniej 0. Potrząc tylko na strone ujemną trudno go oszacować ale prawdopodobnie jest okolo 
0.002 . Taka jest prawdopodobnie rozdzielczość pomiaru xi.  

punkt 2 . To niemożliwe  aby tak było. Gdzieś musi być błąd.  Czy kod w repozytorium jest aktualny? 
Prosze mi wskazać kawałek kodu gdzie selekcjonuje Pan slady do drugiej pary.

**Comment by AddahDraggon** [comment]
Funkcja Patrycji dla pustych wartości daje wartość NaN, a że próbowałem odczytać z pliku którego program nie widział (ze względu na złą ścieżkę), wartości były zwracane puste.

Kod który testuje drugą parę zaczyna się tutaj:
https://github.com/ladamczy/STAR-Analysis/blob/034943e44436833d30a07ddadfaa6ffc824e3956/Inclusive_Analysis/star-upc/src/master_deg_analysis/Inclusive_analysis_with_STUPCV0.cxx#L184

**Comment by PatrycjaMalinowska** [comment]
dodałam komentarz, że trzeba uważać na ścieżkę

**Comment by ladamczy** [comment]
Rozumiem, że te przypadki sa po jakiejś preselekcji.  Prosze o link do kodu (lub opis) jaka była preselekcja i prosze
sprawdzić czy vector_Track.size() jest faktycznie zawsze =4

Prosze zrobić rozkłady  vertex_pair->dcaDaughters() oraz vertex_pair->DCABeamLine() aby sprawdzić jakie te wielkosci 
maja rozkłady moze to pomoże w ocenie dlaczego nie ma żadnego przypadku z kandydatem na vertes_pair. 

Dodatkowo kandydat na K0 powinien się składać ze sladów o przeciwnych znakach. Obecnie akceptuje Pan również pary o tych samych znakach.

**Comment by AddahDraggon** [comment]
Preselekcja jest w plikach Inclusive_Analysis/star-upc/src/master_deg_analysis/preselection1 oraz 2, i jest analogiczna do tej obecnie używanej przez Patrycję
Sprawdziłem wielkość vector_Track.size() - jest stale równa 4
Ta linia gearantuje że znaki w K0będą różne:
https://github.com/ladamczy/STAR-Analysis/blob/63b4e037e11a08ec141b7c6168aa022a1ad9a6f1/Inclusive_Analysis/star-upc/src/master_deg_analysis/Inclusive_analysis_with_STUPCV0.cxx#L150

Rozkłady obu wielkości vertex_pair:
[DCABeamLine.pdf](https://github.com/ladamczy/STAR-Analysis/files/13709054/DCABeamLine.pdf)
[dcaDaughters.pdf](https://github.com/ladamczy/STAR-Analysis/files/13709055/dcaDaughters.pdf)
Wyglądają oba na eksponentę, zakładam że to dobrze?

**Comment by ladamczy** [comment]
Rozkłady vertex_pair wyglądaja dobrze. Czy to sa przypadki w których mamy juz K0_pair? 
Twierdził Pan że jak mamy K0_pair to juz nie mamy vertex_pair spełniających warunki DCA<1.5 cm. 
Chciałbym to zobaczyć. To znaczy rozkłady DCA vertex_pair pod warunkime że mamy juz parę K0_pair.

**Comment by ladamczy** [comment]
czyli 10 000 przypadków ma zarówno K0_pair oraz vertex_pair. To źle Pana zrozumiałem.
Prosze te 1168 K0 odrzucić. 
Prosze narysować decayLengthHypo obu par. 
Histogram 2D masa_k0 vs. decayLengthHypo  dla K0_pair
Różnice pozycji vrt_z obu par.

**Comment by AddahDraggon** [comment]
Zrobione, są to 4 ostatnie histogramy w pliku
[AnaOutput_Inclusive_analysis_with_STUPCV0.pdf](https://github.com/ladamczy/STAR-Analysis/files/13786176/AnaOutput_Inclusive_analysis_with_STUPCV0.pdf)

**Comment by ladamczy** [comment]
- prosze zwiększyć ilość binów na rozkładzie xi_E i xi_W . Chcemy zobaczyć czy tam jest widoczny pik dla xi=0 (po stronie w cos widać). 
- prosze zrobić wykres 2d xi_W vs xi_E
- prosze zrobić wykres który Pan chyba miał w pracy inż.   Delta theta_x vs Delta_theta_y dla protonów. To jest po to aby stwierdzić jak duzo mamy przypadków elestycznych Delta theta_x =0 i Delta_theta_y = 0 i czy powinniśmy zastosowac ciecie antyelastyczne. 
- DeltaZ między K0 i werteksem wygląda dobrze bo na wstepie mamy  wymóg ze wszystkie cztery ślady pochodzą z jednego werteksu. Musi teraz rozszerzyć analize na bardziej skomplikowane przypadki. Na początek prosze zrezygnować 
z jednego werteksu (czyli żadamy cztery ślady z ToF bez żądania jednego werteksu.

**Comment by AddahDraggon** [comment]
Wszystkie poniższe wykresy są jeszcze z żądaniem 1 vertexu:

https://github.com/ladamczy/STAR-Analysis/blob/ae3b2f8aba4e1afa2365c9c3ad9b884100695c46/Inclusive_Analysis/star-upc/src/master_deg_analysis/Preselection2_1vertex_4TOF_charge_kinem_Nhits_clusters.cxx#L151


Zwiększyłem ilość binów 10-krotnie (0.0005/bin):

![XiWcloser](https://github.com/ladamczy/STAR-Analysis/assets/57440874/7a2dce09-2189-45a0-a1ba-d38668a4643c)
![XiEcloser](https://github.com/ladamczy/STAR-Analysis/assets/57440874/c9ffffa1-057e-4252-a46e-96969c176c01)


Na wykresie 2D te piki tworzą taką jakby wysepkę blisko 0:

![Xi2D](https://github.com/ladamczy/STAR-Analysis/assets/57440874/6a286fa2-ebe4-412b-967c-4560ce624d20)


U siebie w pracy zrobiłem sumy pędów poprzecznych, ale też zrobiłem na wszelki wypadek wykres różnicy kątów theta:

![differencetheta](https://github.com/ladamczy/STAR-Analysis/assets/57440874/5360be34-94a2-4a58-b1f8-41041c5c5d06)
![summomenta](https://github.com/ladamczy/STAR-Analysis/assets/57440874/a9caad6e-78bc-4ea4-86fc-c1cf3d35d6f6)

Sądzę że cięcia na pęd poprzeczny by pasowały lepiej - w obu "oczkach" o wyższej intensywności jest ok. 1000 przypadków, ale to z pędem jest wyraźniejsze.

**Comment by ladamczy** [comment]
bo powinniśmy rysowac sume katów a nie róznice wtedy wnioski z analizy katowej i pedowej będa takie same. 

Natomiast jest jakiś problem z rekonstrukcja xi  ten pik powinien być w xi=0 a jest jakieś przesuniecie szczególnie widoczne po stronie E. 

Ciecie antyelastyczne powinno być na przypadki które równocześnie sa w piku xiE=xiW=0 oraz py=px=0 
Trzeba by wziąść +- 3 sigma wokół 0  oczywiście w przypadku xi trzeba wziąśc 3 sigma wokół środka tego obszaru o wiekszej aktywności.  Być może trzeba wprowadzić poprawki addytywne do xi tak aby ten pik był w 0.

**Comment by AddahDraggon** [comment]
Sam fit na Xi na wykresie 2D wygląda dobrze:

[Xi2Dfit.pdf](https://github.com/ladamczy/STAR-Analysis/files/13799308/Xi2Dfit.pdf)

Ale przy próbie pokazania fitu na rzutach na osie pojawiają się dwa problemy:

[XiProfile.pdf](https://github.com/ladamczy/STAR-Analysis/files/13799311/XiProfile.pdf)

Jeden to to, że dalsza część wykresu Xi "zasłania" ten pik, który chcę wydielić.
Drugim jest problem skalowania wysokości funkcji fitowanej na wykresie 2D do rzutu na 1D.
Pierwszy problem zakładam że można obejśc po prostu robiąc rzuty tylko tego piku do którego dopasowujemy.
Nie do końca wiem natomiast jak się zabrać do drugiego - pomysły jakie mam to np. w jakiś sposób przeskalować przez np. stosunek wysokości najyższych binów, bądź dopasować osobno gausjan do takiego wyciętego fragmentu, sprawdzić jego wysokość i wtedy to użyć?
Te wykresy są robocze, do prezentacji je doszlifuję wizualnie.

**Comment by ladamczy** [comment]
jesli fit 2D wyglada dobrze i chi/ndf jest dobre to nie ma powodu takiemu fitowi nie ufać. 
Jeden komentarz jaki miałem to ilość binów powinna być większa bo wydaje mi się że jesteśmy blisko sutuacji gdy szerokość gaussa to jeden bin. a to nie jest dobre. 

Wydaje mi sie że nie sugerowałiśmy pokazania fitu na rzutach , tylko zrobienie fitu do rzutów to cos innego.
Oczywiście fit do rzutu niewiele pomoże (jak widac na obrazku) natomiast fit do rzutu tylko obszaru gdzie jest pik 
z pewnościa pomoze i pewnie rozwiąże równiez problem normalizacji. Ten problem normalizacji pewnie pochodzi z tego ze rysując fit 2D nie powinien Pan rzutowac tej funkcji tylko wycałkowac po drugim wymiarze.

**Comment by AddahDraggon** [comment]
Spróbowałem dopasować pojedynczego gaussa do wykresu 2D xi oraz sumę dwóch do wykresu pędów poprzecznych, dla dwóch różnych ilości binów (czerwony okrąg wyznacza granicę 3sigma):
[p1.pdf](https://github.com/ladamczy/STAR-Analysis/files/13806237/p1.pdf)
[p2.pdf](https://github.com/ladamczy/STAR-Analysis/files/13806235/p2.pdf)
[Xi1.pdf](https://github.com/ladamczy/STAR-Analysis/files/13806239/Xi1.pdf)
[Xi2.pdf](https://github.com/ladamczy/STAR-Analysis/files/13806236/Xi2.pdf)
Dla rzadszych binów sprawdziłęm również jak wygląda wykres masy K0 po odjęciu ww. zderzeń elastycznych:
[K0.pdf](https://github.com/ladamczy/STAR-Analysis/files/13806245/K0.pdf)
Obawiam się że przy tych dopasowaniach te cięcia nie są zbyt skuteczne (chociaż same piki na wykresach 1D xi są ładnie usuwane):
[XiW](https://github.com/ladamczy/STAR-Analysis/assets/57440874/877685fa-f75d-4128-9a46-24f0f1a2d496)
[XiE](https://github.com/ladamczy/STAR-Analysis/assets/57440874/b2a01a07-94b7-43f4-8dce-de60e4762616)
Czy mam dopasowywać wielkość binów tak, żeby zbliżyć chi2/ndf do 1 czy raczej np. kombinować z dodaniem do gaussa jakiegoś tła w postaci wielomianu dwóch zmiennych?

**Comment by ladamczy** [comment]
Prosze juz nie tracić czasu na te fity. Ich jakość nigdy nie będzie dobra bo nie wiemy jak wygląda rozkład poza 
pikiem xi~0 i nie ma sensu go modelować bo to nie jest istotne na obecnym etapie

Lepiej powtórzyć fity do danych zero-bias gdzie będziemy mieli  właściwie tylko przypadki elastyczne. 
Nie wiem jaka była motywacji fitu do sumy dwóch gaussow? Ale zostawmy to i przejdżmy do analizy 
danych zero-bias.

Już to wstępne ciecie antyelastyczne spełnia swoje zadanie. 
Wycinamy przypadki z xi których nie widzimy w MC. 
Prosze się nie martwić ze wycinamy troche K0. Bo to sa złę K0. To przypadkowa koincydencja 
protonów w RP i K0 w TPC. To jest wlaśnie tło które chcemy odrzucić.

**Comment by ladamczy** [comment]
Tutaj dobrze by zrobić porównanie z poziomem true z PYTHIA8 rozmywając xi_true o 0.002 . 

Oraz rozszerzyć analize na inne kanały
- rezygnacja z ciecia na jeden werteks 
- wieksza ilość sladów z TOF w wierzchołku pierowtnym 
- brak dodatkowych sladów (widzimy tylko K0)

No i trzeba zacząć patrzeć na Lamba, LmbdaBar

**Comment by AddahDraggon** [comment]
Patrzenie na Lambdę i K0 wprowadzić przez sprawdzenia czy dane cząstki są w obrębie 3sigma dla danego rodzaju (w kolejności sprawdzania elektron, kaon, proton, pion) czy w jakiś inny sposób?

**Comment by ladamczy** [comment]
Na poczatek sugeruje aby nie patrzeć wogóle na identyfikacje cząstek. 
Czyli dla K0 zakładamy że obie czastki to piony
Dla Lambda zakładamy ze dodatnia to proton a ujemna to pion
Dla Lambdabar zakładamy że dodatnia to pion a ujemna to (anty)proton 

Identyfikujemy K0 i Lambdy tylko na podstawie rozkładu masy niezmienniczej pary. 

Jeśli się okaże że jednak tło jest zbyt duże to możemy nałozyć warunek +- 3 sigma na każdą z czastek.
Czyli np. dla Lambda sprawdzamy że cząstka dodatnia ma +-3 sigma_proton a ujemna +-3 sigma_pion
Podobnie dla Lambdabar i K0. 

Jesli nadal tło będzie zbyt duże to możemy sprawe bardziej komplikować i np. szukając protonu 
możemy nie tylko żądać +-3 sigma_proton ale również że nie jest pionem abs(sigma_pion)>3 .

Ale tak jak napisałem na poczatku lepiej nie patrzeć wcale na prawdopodobieństwa że czastka jest taka a nie inna.

**Comment by ladamczy** [comment]
Niech Pan zacznie od minimalnej selekcji:

1.  Po każdej stronie jeden i tylko jeden proton z  0.005<xi< 0.08 (<0.2 dla trgera bez weta BBL)
2. Ciecia antyelestyczne jak jak wynika z analizy zero-bias 
3. Przynajmniej dwa slady z ToF  w  zakresie pt,eta, nhits jak w analizie Patrycji

4. Dla takiej próbki szukamy K0 z cieciami DCAbeamline, DCAduaghters,decaylenghthHypo and cos(poinitng angle)
jak w analizie Patrycji , oba slady z ToF

Robimy rozkład masy niezmienniczej pary w szerokim zakresie masy (jak w analizie Patrycji)

5. Patrzymy na rozkład ilości K0 w waskim zakresie masy (jak w analizie Patrycji). Chodzi o ilość na przypadek. 
6. Patrzymy na rozkład ilości dodatkowych sladów (oprócz tych przypisanych do K0 w wąskim zkresie mas)

Jak Pan to będzie miał to pójdziemy dalej  (jako input do V0 findera prosze przyjąć vertex=0,0,0

**Comment by AddahDraggon** [comment]
Odnośnie cięć na xi: dobrze rozumiem że afterburner powinienem stosować przed tymi cięciami?

**Comment by ladamczy** [comment]
tak,   na poczatku afterburner potem jakiekolwiek ciecia.

**Comment by AddahDraggon** [comment]
Przy "dodatkowych śladach" chodzi o K0 poza wąskim zakresem masy czy o piony które je tworzą?

**Comment by ladamczy** [comment]
Przez "ślady" rozumiem cząstki naładowane mierzone w TPC. "Dodatkowe ślady" to wszsytkie slady w TPC
(po cieciach i znaczowane z ToF) pomniejszone o ilość pionów które tworzą K0 w wąskim zakresie masy. 
Generalnie proces który badamy to:
p+p-> p+K0+X+p lub p+p-> p+nK0+X+p  przy produkcji n K0. 
Co możemy powiedzieć o stanie X?
Jaka jest krotność sladów w tym stanie X?  Czy wierzchołek stanu X pokrywa sie z wierzchołkiem produkji K0, ...

**Comment by AddahDraggon** [comment]
OK - wstępne wyniki (na niecałej próbce) będą wieczorem, z jakiegoś pwoodu analiza zajmuje znacznie dłużej niż przypuszczałem

**Comment by AddahDraggon** [comment]
Przy produkcji nK0 gdy mamy powiedzmy 2 zrekonstruowane K0 posiadające jeden wspólny ślad, czy wprowadzamy jakiegoś rodzaju selekcję np. na podstawie odległości od masy tablicowej K0, czy póki co ten problem pomijamy?

**Comment by ladamczy** [comment]
Teraz prosze przyjąć tę parę która ma mniejsze DCADaughters . 

Natomiast w przyszłości trzeba pomysleć o jakimś cieciu które wymusi pewna isolację K0 od reszty sladów. 
Generalnie jeśli mamy trzy ślady które  tworzą dwójke kandydatów na K0 to znaczy że one najprawdopodobnie
nie sa K0 i obu kandydatów trzeba odrzucić.  Do tego problemu wrócimy jako oddzielne issue bo to nie jest trywialne.

**Comment by AddahDraggon** [comment]
Rozkład masy par (wszystkich) w szerokim zakresie mam, rozkładu wąskiego nie mam, bo z jakiegoś powodu wypełnia histogram zerami, naprawię to jutro

![canvas](https://github.com/ladamczy/STAR-Analysis/assets/57440874/c979d80d-1c4e-486a-ac8b-da238a6f6236)

Niepokoi mnie że pik nie jest w dobrej pozycji, spróbuję jeszcze sprawdzić czy po usunięciu korekt do nachyleń wiązki (do wyliczenia używałem getVertex(0), chyba że też go powinienem zamienić na (0,0,0)?) coś się zmieni

**Comment by ladamczy** [comment]
pik jest przesuniety jest zbyt szeroki i zbyt niski. Może mi /pan wskazać w kodzie gdzie Pan wypełnia ten histogram?

**Comment by AddahDraggon** [comment]
https://github.com/ladamczy/STAR-Analysis/blob/bf971585e3893feeabba6e29ecba77e2cf124e02/Inclusive_Analysis/star-upc/src/master_deg_analysis/Wide_K0_search/Inclusive_analysis_with_STUPCV0_with_extended_range_noAfterburner.cxx#L207

**Comment by AddahDraggon** [comment]
Poprawiło się:

![canvas](https://github.com/ladamczy/STAR-Analysis/assets/57440874/47dab3d6-bad2-4b4b-b163-e2f318de1264)

Sortowanie K0 ze względu na DCAdaughter nadal nie działa, ale dzisiaj powinienem je naprawić

**Comment by ladamczy** [comment]
Czy to jest pełna statystyka?

Oprócz rozkładu krotności K0 ( w wąskim zakresie masy) prosze pomysleć o plotach:


1. Krotności dodatkowych sladów z ToF ?
2. Krotności werteksów. 
3. Krotności śladów z ToF przypisanych do werteksu id=0 (best werteks) pomniejszonych o ilość sladów z K0 jesli sa przypisane do tego samego werteksu. 
 4. róznicy między położeniem (współrzędna z) werteksu (id=0) a położeniem werteksu produkcji K0.
5. Rozkad masy pary pionów (kandydatów na K0) z dodatkowym cieciem   decaylenghthHypo>3 and cos(poinitng angle)>0.925

**Comment by AddahDraggon** [comment]
Jest to fragment na jednym z dwóch przedziałów wymienionych w https://github.com/ladamczy/STAR-Analysis/issues/16#issuecomment-1895616452, pokazujący że obecna selekcja w szerokim zakresie działa - gdy selekcja w wąskim zakresie też będzie działać, to prześlę pełne wyniki + ploty

**Comment by AddahDraggon** [comment]
Dodałem powyższe histogramy, wyniki przesyłam zapakowane poniżej:

[CPT&CPTnoBBCL.zip](https://github.com/ladamczy/STAR-Analysis/files/14551052/CPT.CPTnoBBCL.zip)

Z ciekawości sprawdziłem też co się stanie po zastosowaniu cięcia na dE/dx na piony (|sigma|<3), i wydaje się to lekko zmniejszać tło.

Jest tam też kilka wykresów odnośnie wierzchołków, bo nie jestem do końca pewien w jaki sposób są one tworzone - pewna mała ilość przypadków nie ma vertexu o Id 0, albo ilość wierzchołków pierwotnych (getNPrimVertices) jest większa od całkowitej liczby wierzchołków w analizowanym przypadku. Ponadto, tablica z wszystkimi wierzchołkami (mUPCVertices w StUPCEvent) jest oznaczona komentarzem jako "  //number of primary vertices in event", co też trochę zwiększa moje wątpliwości.

Chciałbym się też zapytać, czy dobrze rozumiem że zmienna mDcaToPrimaryVertex w StUPCV0 to jest odległość największego zbliżenia prostej zawierającej tor lotu K0 do wierzchołka podanego przy inicjalizacji zmiennej?

**Comment by ladamczy** [comment]
Ciecie na piony (|sigma|<3) lekko zmniejsza tło i generalnie zwieksza stosunek K0/tło ale równoczesnie zmniejsza 
ilość K0 i wprowadza pewien błąd systematyczny na poprawkę która bedziemy musieli zastosować by poprawić na te
straty. Dlatego tak długo jak sie bedzie dało nie będziemy stosować ciecia  na piony (|sigma|<3)

"ewna mała ilość przypadków nie ma vertexu o Id 0"
Nie ma wogóle werteksu? Czy ma vertex np. o id=1 ale nie ma o id=0. Tak jakby była dziura.

Werteksy sa tworzone podczas rekonstrukcji i tworzenia tak zwanych muDST. Na tym etapie wymaga sie aby vertex miał 
przynajmniej jeden slad zmaczowany z ToF lub klastrem w kalorymetrze elektromagnetycznym.  ToF ma trójstopniowa 
segemenatcje: tray (dzieli ToF na przedziały w kącie polarnym phi) mamy oddzielne tray'e dla eta<0 i eta>0. Tray dzieli się na moduły (wzdłuz osi-Z) odpowiadające przedziałom w eta(kącie zymutalnym). Moduły dzielą się jeszcze na cele (6 albo 10 juz teraz nie pamietam) Cele odpowidają jeszcze węższym zakresom eta.  Maczowanie podczas produkcji muDst jest 
tylko na poziomie tray,modul i werteksy primary sa numerowane od 0 do getNPrimVertices-1. 

Podczas tworzenia UPCDst ponownie wykonuje się maczowanie z ToF ale tym razem juz biorąc pod uwagę cele, czyli o jeden poziom dokładniej. Część sladów która była zmaczowana na poziomie tray,modul nie jest zmaczowana biorąc jeszcze 
pod uwagę cele. Jeśli jakiś vertex utraci wszystkie swoje slady z ToF to nie jest zapisywany w tablicu z wierzchołkami. 
Dlatego tablica z wszystkimi wierzchołkami może być krótsza od getNPrimVertices. 
Natomiast nie jestem pewien czy id się wtedy zmienia czy nie ale jesli widzi Pan przypadki gdzie jest werteks id=1 a nie ma
id=0 to znaczy że id pozostaje takie jakie jest w muDST.

Zmienna mDcaToPrimaryVertex w StUPCV0 to odległość najmniejszego zbliżenia  prostej zawierającej tor lotu K0 do wierzchołka podanego przy inicjalizacji K0.

Jesli chodzi o histogramy to wszystkie oprócz rozkładu krotności K0 i rozkładów masy niezmienniczej prosze warunkować istnieniem przynajmniej jednego K0.  Ewentualnie może Pan robic dwie wersje tego samego histogramu 
z warunkiem na istnienie przynajmniej jednego K0 oraz bez tego warunku. 

Ilość przypadków z dwoma K0 do jednego K0 jest jak 1/500 , mysle że na obecnym etapie moze Pan zapomnieć 
o problemie dublowania sladów w K0. Jak się tak zdarzy to prosze odrzucić przypadek (oba K0).

Nie rozumiem dlaczego ilość K0 z  decaylenghthHypo>3 && cos(poinitng angle)>0.925 jest wieksza niż 

decaylenghthHypo<3 || cos(poinitng angle)>0.925

**Comment by AddahDraggon** [comment]
Wydaje mi się, że z wprowadzeniem globalnych śladów oraz poprawą wszystkich cięć można zamknąć to issue.
